site: マスナリジュン
title: マスナリジュンのBlog
description: >-
  
googlewebfonts: Fira+Code:wght@400;500;700
lang: ja
timezone: Asia/Tokyo
repo:  # site repo [optional]
data-theme: "light" # default theme "dark" | "light"

author:
  name: msnrjn
  bio: 
  username: msnrjn # general username
  github:  # github username
  twitter: msnrjn # twitter username
  email:  # email adress

# URL settings
url: "https://msnrjn.net" #
baseurl: "" # leave blank if not wishd
permalink: "https://msnrjn.net/"
permalink: pretty 


markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge


exclude:
  - .jekyll-cache
  - .obsidian
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - CONTRIBUTING.md
  
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-relative-links

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:year/:month/:day/:slug
  
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

relative_links:
  enabled:     false
  collections: false



theme: jekyll-theme-cayman